### ISSUE TITLE
Credentials exposed on /teams endpoint

### ISSUE THREAD

**Issue by mcalr3** [linode/apl-core#1632]
Similar to a bug we reported on the /settings endpoint, there are also credentials exposed on the /teams endpoint.

Both team-admin and team-* users can access this and can gain access to the otomi-admin password.

You can see the endpoint by using F12 developer tools and using the Network tab to see the response from this endpoint.

Using Otomi v2.11.0
![image](https://github.com/redkubes/otomi-core/assets/19345458/b18f7fe8-4016-4c59-a487-11f1d8154d86)

**Comment by CasLubbers** [comment]
Hi,

Thank you for your contribution. This issue has been resolved in the API on the main branch. We will be releasing a new patch for version 2.11, which will include this fix. The patch should be available later this week.

Best regards,
Cas

**Comment by CasLubbers** [comment]
Hi, 

We've created a patch release 2.11.6 if you do `helm repo update` and `helm search repo otomi` it will show 2.11.6 as latest. This contains the fix for the /teams endpoint.
Also our newest 3.0 release it out in our new repo `apl`. https://github.com/linode/apl-core/releases

**Comment by mcalr3** [comment]
@CasLubbers We just upgraded to 2.11.6 and tested this out but unfortunately the issue is still present. The team-admin password this time though doesn't seem to be exposed, but all the other teams passwords (oidc password?) are still exposed. See below:

![image](https://github.com/user-attachments/assets/a1952968-3375-4305-a6e6-200aa2b7ad89)
<img width="657" alt="image" src="https://github.com/user-attachments/assets/397f06d5-f17f-4d91-98f0-7a1da6a00822">

**Comment by CasLubbers** [comment]
Thats weird, it didn't update the Otomi API version which contains the fix. It should have updated to 2.9.2 (https://github.com/linode/apl-core/commit/8d4555777e4567a59a04ecb4e21a570a5f5215d3#diff-1c4cd801df522f4a92edbfb0fea95364ed074a391ea47c284ddc078f512f7b6aR1). You can only change this directly in the ArgoCD application of otomi-api it needs to be set to the latest docker image v2.9.2 (https://hub.docker.com/r/otomi/api/tags?name=2.9)
